### PR TITLE
Correctly resolve function runtime classpath in Maven plugin. Fixes #30

### LINKED ISSUE #30: Maven: function-maven-plugin uses compile classpath instead of runtime classpath
When you configure `function-maven-plugin` and do `mvn function:run` the classpath used contains only `compile` scoped dependencies and not `runtime` dependencies which results in failures at runtime such as:

```
[ERROR] Failed to execute goal com.google.cloud.functions:function-maven-plugin:0.9.1:run (default-cli) on project hello-world-cloud-function: Execution default-cli of goal com.google.cloud.functions:function-maven-plugin:0.9.1:run failed: A required class was missing while executing com.google.cloud.functions:function-maven-plugin:0.9.1:run: io/micronaut/servlet/http/ServletHttpHandler
```

### PR DESCRIPTION
**Pull request by graemerocher**
This PR correctly builds the runtime classpath for the function. The current implementation only includes compile dependencies which is broken for all but the most trivial cases.

### CODE REVIEW

**Comment by graemerocher** [comment]
Any hope this will be merged?

**Comment by grant** [comment]
Hi @graemerocher, it looks like we could get a couple reviews for this framework. I've sent a review request to the main maintainer.

**Comment by graemerocher** [comment]
Thanks

File: invoker/function-maven-plugin/src/main/java/com/google/cloud/functions/plugin/RunFunction.java [hunk 1]
```diff
@@ -1,17 +1,14 @@
 package com.google.cloud.functions.plugin;
 
 import com.google.cloud.functions.invoker.runner.Invoker;
+import org.apache.maven.plugin.AbstractMojo;
+import org.apache.maven.plugin.MojoExecutionException;
+import org.apache.maven.plugins.annotations.*;
```
Comment (eamonnmcmanus) [inline invoker/function-maven-plugin/src/main/java/com/google/cloud/functions/plugin/RunFunction.java:6]: Would you mind putting these imports back the way they were? Google style requires imports to be sorted lexicographically with no blank lines and no wildcard imports.

File: invoker/function-maven-plugin/src/main/java/com/google/cloud/functions/plugin/RunFunction.java [hunk 2]
```diff
@@ -79,4 +77,7 @@ public void execute() throws MojoExecutionException {
       throw new MojoExecutionException("Could not invoke function", e);
     }
   }
+
```
Comment (eamonnmcmanus) [inline invoker/function-maven-plugin/src/main/java/com/google/cloud/functions/plugin/RunFunction.java:80]: I don't think we need these extra blank lines?
